/**
 * GET /auth/sso
 * SSO handler route - verifies token and creates session
 *
 * Query params:
 * - token: SSO token generated by POST /api/v2/auth/sso
 * - redirect: URL to redirect to after successful login
 *
 * This route:
 * 1. Verifies the SSO token
 * 2. Creates a user session
 * 3. Redirects to the specified URL (or /admin by default)
 */

import { useLogger } from '@create-studio/shared/utils/logger'
import { UserRepository, SiteRepository } from '~~/server/utils/database'
import { jwtVerify } from 'jose'

interface SSOTokenPayload {
  type: 'sso'
  user_id: number
  site_id: number
  email: string
}

export default defineEventHandler(async (event) => {
  const { debug, public: { rootUrl } } = useRuntimeConfig()
  const config = useRuntimeConfig()
  const logger = useLogger('Auth:SSO', debug)

  // Get query params
  const query = getQuery(event)
  const token = query.token as string
  const redirect = (query.redirect as string) || '/admin'

  // Error redirect helper
  const errorRedirect = (message: string) => {
    const errorUrl = new URL('/auth/login', rootUrl)
    errorUrl.searchParams.set('error', message)
    return sendRedirect(event, errorUrl.toString())
  }

  if (!token) {
    logger.error('SSO: Missing token')
    return errorRedirect('Missing SSO token')
  }

  // Verify token
  const secret = config.servicesApiJWTSecret || process.env.NUXT_SERVICES_API_JWT_SECRET
  if (!secret) {
    logger.error('SSO: JWT secret not configured')
    return errorRedirect('Server configuration error')
  }

  const secretKey = new TextEncoder().encode(secret)

  let payload: SSOTokenPayload
  try {
    const { payload: decoded } = await jwtVerify(token, secretKey)
    payload = decoded as unknown as SSOTokenPayload

    // Verify token type
    if (payload.type !== 'sso') {
      logger.error('SSO: Invalid token type', { type: payload.type })
      return errorRedirect('Invalid SSO token')
    }
  }
  catch (error: any) {
    logger.error('SSO: Token verification failed', { error: error.message })

    // Check for expiration
    if (error.code === 'ERR_JWT_EXPIRED') {
      return errorRedirect('SSO link has expired. Please generate a new one.')
    }

    return errorRedirect('Invalid or expired SSO token')
  }

  // Get user
  const userRepo = new UserRepository()
  const user = await userRepo.findById(payload.user_id)

  if (!user) {
    logger.error('SSO: User not found', { userId: payload.user_id })
    return errorRedirect('User not found')
  }

  // Verify user email matches token
  if (user.email !== payload.email) {
    logger.error('SSO: Email mismatch', { tokenEmail: payload.email, userEmail: user.email })
    return errorRedirect('Invalid SSO token')
  }

  // Get user's sites for session
  const siteRepo = new SiteRepository()
  const sites = await siteRepo.getUserCanonicalSites(user.id)

  // Create session
  await setUserSession(event, {
    user: {
      id: user.id,
      email: user.email,
      firstname: user.firstname,
      lastname: user.lastname,
      avatar: user.avatar,
      validEmail: user.validEmail ?? false,
    },
    sites: sites.map(site => ({
      id: site.id,
      url: site.url,
      name: site.name
    })),
    loggedInAt: new Date().toISOString()
  })

  logger.info('SSO: Session created', {
    userId: user.id,
    siteId: payload.site_id,
    redirect
  })

  // Validate and sanitize redirect URL
  let redirectUrl = redirect

  // Ensure redirect is relative or same-origin
  if (redirectUrl.startsWith('http')) {
    try {
      const redirectParsed = new URL(redirectUrl)
      const baseParsed = new URL(rootUrl)
      if (redirectParsed.host !== baseParsed.host) {
        // External redirect not allowed - use default
        redirectUrl = '/admin'
      }
    }
    catch {
      redirectUrl = '/admin'
    }
  }
  else if (!redirectUrl.startsWith('/')) {
    // Must be relative path
    redirectUrl = '/admin'
  }

  return sendRedirect(event, redirectUrl)
})
