/**
 * April 2026 Publisher Survey — SurveyJS format
 *
 * Ordering principle: NPS first (always), then blocks and questions
 * sequenced from easier/factual to harder/more abstract.
 * Psychologically light questions (categories, directional choices) run
 * before money/disclosure or open-ended reflection.
 */

export const aprilSurveyDefinition = {
  title: 'Create Publisher Survey',
  description: 'Help shape the next chapter of Create! Finish this 5-10 minute survey to unlock 50% off your first year of Create Pro.',
  closes_at: '2026-04-30T23:59:59-04:00',
  questionsOnPageMode: 'singlePage',
  showProgressBar: 'top',
  progressBarType: 'questions',
  showQuestionNumbers: 'off',
  questionErrorLocation: 'bottom',
  pages: [
    {
      name: 'nps',
      title: 'NPS',
      elements: [
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'nps_score',
          title: 'On a scale of 0–10, how likely are you to recommend Create to another publisher?',
          isRequired: true,
          rateMin: 0,
          rateMax: 10,
          minRateDescription: 'Not at all likely',
          maxRateDescription: 'Extremely likely',
        },
        {
          type: 'comment',
          name: 'nps_reason',
          title: "What's the main reason for your score?",
          isRequired: false,
        },
      ],
    },
    {
      name: 'about_you',
      title: 'About you',
      elements: [
        {
          type: 'radiogroup',
          name: 'site_type',
          title: 'What best describes your site?',
          isRequired: true,
          choices: ['Food blog / Recipe site', 'DIY or craft', 'Home & garden', 'Parenting or lifestyle', 'Travel'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'tenure',
          title: 'How long have you been publishing?',
          isRequired: true,
          choices: ['Less than 1 year', '1–3 years', '3–7 years', '7–15 years', '15+ years'],
        },
        {
          type: 'radiogroup',
          name: 'ad_network',
          title: 'Which ad management provider do you work with?',
          isRequired: false,
          choices: ['Raptive', 'Mediavine / Journey by Mediavine', 'Ezoic', 'Google AdSense only', 'Not monetized with display ads'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'monthly_sessions',
          title: 'Approximate monthly sessions on your site?',
          isRequired: true,
          choices: ['Under 10k', '10k–50k', '50k–200k', '200k–1M', '1M+'],
        },
        {
          type: 'radiogroup',
          name: 'annual_revenue',
          title: 'Approximate annual revenue from the site? (Optional — helps me price fairly)',
          isRequired: false,
          choices: ['Under $10k', '$10k–$50k', '$50k–$150k', '$150k–$500k', '$500k+', 'Prefer not to say'],
        },
      ],
    },
    {
      name: 'state_of_industry',
      title: 'State of the industry',
      elements: [
        {
          type: 'radiogroup',
          name: 'traffic_trend',
          title: 'How is your traffic trending vs. 12 months ago?',
          isRequired: true,
          choices: ['Up significantly', 'Up slightly', 'Flat', 'Down slightly', 'Down significantly'],
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'ai_worry',
          title: 'How worried are you about AI Overviews and AI chat tools impacting your traffic?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not at all worried',
          maxRateDescription: 'Extremely worried',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_know_next_step',
          title: 'I feel like I know what to do next to grow my site.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_tools_keeping_up',
          title: 'The tools and plugins I use are keeping up with how publishing is changing.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'comment',
          name: 'biggest_worry',
          title: 'What is your single biggest worry about your publishing business right now?',
          isRequired: false,
        },
      ],
    },
    {
      name: 'tools_and_spend',
      title: 'Current tools',
      elements: [
        {
          type: 'checkbox',
          name: 'current_paid_tools',
          title: 'Which of these do you currently pay for?',
          isRequired: true,
          choices: [
            'WordPress hosting',
            'Recipe / content plugin (other than Create)',
            'SEO tool (Ahrefs, Semrush, etc.)',
            'Email service (Kit, ConvertKit, Flodesk, etc.)',
            'Email list cleaning / deliverability',
            'Pinterest scheduler',
            'Image CDN / optimization',
            'Site speed tools',
            'Virtual assistant',
            'Freelance developer',
            'Freelance designer',
            'Accounting / bookkeeping',
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'checkbox',
          name: 'competing_plugins_used',
          title: 'Which other recipe card or content plugin have you used, if any?',
          isRequired: false,
          choices: ['WP Recipe Maker', 'Tasty Recipes', 'Recipe Card Blocks', 'Cookbook', 'Zip Recipes', 'None'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'annual_tooling_spend',
          title: 'Roughly, how much do you spend annually on site tools, services, and contractors?',
          isRequired: true,
          choices: ['Under $500', '$500–$2,000', '$2,000–$5,000', '$5,000–$15,000', '$15,000–$50,000', '$50,000+'],
        },
        {
          type: 'comment',
          name: 'stack_frustration',
          title: 'Biggest frustration with your current tool stack?',
          isRequired: false,
        },
      ],
    },
    {
      name: 'create_specifically',
      title: 'Your Create experience',
      elements: [
        {
          type: 'checkbox',
          name: 'create_primary_use',
          title: 'What do you use Create primarily for?',
          isRequired: true,
          choices: ['Recipe cards', 'How-to / tutorial cards', 'Lists / roundups', 'All of the above'],
        },
        {
          type: 'checkbox',
          name: 'create_dislikes',
          title: "What don't you love about Create right now? (Select all that apply)",
          isRequired: true,
          choices: [
            'Feels slow or affects my site speed',
            'Features are confusing or hard to set up',
            'Limited theme / styling options',
            "Doesn't match my site's design well",
            'Compatibility issues with my WordPress theme',
            'Compatibility issues with other plugins',
            'Bugs or glitches',
            'Missing features I need',
            'Too expensive for what I get',
            'Onboarding / first-time setup was rough',
            'Documentation / help is hard to find',
            'Support response is slow',
            "Nothing, I'm happy with Create!",
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'comment',
          name: 'create_improvement',
          title: 'If you could improve one thing in Create today, what would it be?',
          isRequired: false,
        },
        {
          type: 'ranking',
          name: 'feature_priorities_top_3',
          title: 'Which of these would you most want to see in Create next? Rank your top 3.',
          isRequired: true,
          choices: [
            'Author cards (highlight *you*!)',
            'Browser extension for saving links / products while browsing',
            'Mobile app for readers',
            'Community / network of Create publishers',
            'Content-discovery platform for readers',
            'Built-in AI recipe / content importer',
            'Built-in email capture / list features',
            'Speed & performance optimizations',
          ],
          showOtherItem: true,
          otherText: 'Integrations with other platforms and tools',
          selectToRankEnabled: true,
          selectToRankAreasLayout: 'horizontal',
          maxSelectedChoices: 3,
        },
        {
          type: 'comment',
          name: 'missing_to_be_indispensable',
          title: "What's missing from Create that would make it indispensable to you?",
          isRequired: false,
        },
        {
          type: 'ranking',
          name: 'pro_feature_excitement',
          title: 'Which existing Pro features are you most excited to use or curious to try? Rank your top 3.',
          isRequired: true,
          choices: [
            'Interactive cook mode (step-by-step with timers and progress)',
            'Premium card themes',
            'Servings adjustment',
            'Unit conversion (metric / imperial)',
            'Interactive checklists (check off ingredients and steps)',
            'Review management (reply to and feature reader reviews)',
            'Featured reviews block',
            'Custom CSS',
            'Custom ad network in Interactive Mode',
            'Customize Interactive Mode (via Create Studio)',
          ],
          selectToRankEnabled: true,
          selectToRankAreasLayout: 'horizontal',
          maxSelectedChoices: 3,
        },
      ],
    },
    {
      name: 'ai',
      title: 'AI',
      elements: [
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_known_by_name_as_expert',
          title: 'I want to be known by name as a go-to expert in my niche — not just run a site that gets traffic.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'radiogroup',
          name: 'biggest_win',
          title: 'Which of these would feel like the biggest win?',
          isRequired: true,
          choices: [
            'Someone recommends me by name to a friend',
            'An AI assistant recommends my content by name',
            'A brand reaches out for a paid partnership',
            'My site earns enough to replace a full-time income',
            'A reader tells me my content became their household go-to',
          ],
        },
        {
          type: 'checkbox',
          name: 'ai_tools_used',
          title: 'Which AI tools do you currently use for your publishing work?',
          isRequired: true,
          choices: ['ChatGPT', 'Claude', 'Gemini', 'Perplexity', 'Midjourney / image AI', 'AI writing tools (Jasper, etc.)', 'None'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'ai_in_create_comfort',
          title: 'How comfortable are you with AI features being built into Create?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not comfortable',
          maxRateDescription: 'Very comfortable',
        },
        {
          type: 'checkbox',
          name: 'ai_features_wanted',
          title: 'Which AI-powered features would you actually use?',
          isRequired: false,
          choices: [
            'Recipe import from text / post content / etc.',
            'Auto-generate post draft from card content',
            'SEO metadata suggestions / Create card SEO enhancement (keywords, etc.)',
            'Content ideas based on my existing library',
            'Answering reader questions on-site',
            'None',
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
      ],
    },
    {
      name: 'positioning',
      title: 'What matters most',
      description: 'Rate your agreement with each statement (1 = strongly disagree, 5 = strongly agree).',
      elements: [
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_engagement_matters_more',
          title: 'Keeping readers engaged on my site matters more to me now than it did two years ago.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_own_relationship',
          title: "I'd rather own the reader relationship (email, on-site engagement) than rely on Google traffic.",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_community_over_library',
          title: 'I want my site to feel more like a community and less like a content library.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_pay_more_to_compete_with_ai',
          title: "I'd pay more for a plugin that actively helps me compete with AI-generated content.",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
      ],
    },
    {
      name: 'bigger_bets',
      title: 'Big ideas: platform, community, extension',
      elements: [
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'browser_extension_interest',
          title: 'How interested would you be in a browser extension for saving links and products to Create Lists while you browse?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not interested',
          maxRateDescription: 'Very interested',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'publisher_community_interest',
          title: "How interested would you be in a private community of Create publishers where you could rate & review each other's cards and find relevant links for each other's lists/roundups?",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not interested',
          maxRateDescription: 'Very interested',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'discovery_app_interest',
          title: 'Imagine a reader-facing mobile app where people discover recipes and guides from Create publishers: users could follow topics, rate content, and get recommendations. Your content could be included (opt-in), with monetization. How would you feel about this?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not interested',
          maxRateDescription: 'Very interested',
        },
        {
          type: 'radiogroup',
          name: 'discovery_app_model_pref',
          title: 'If such an app existed, which monetization model would you prefer?',
          isRequired: false,
          choices: [
            'Revenue share: app monetizes (ads / affiliates / subscriptions), we split',
            'Pro-only perk: A Pro-subscriber benefit, in-app monetization is yours',
            'Flat licensing fee paid to me',
            "I wouldn't participate",
          ],
          showOtherItem: true,
          otherText: 'Another idea',
        },
      ],
    },
    {
      name: 'services',
      title: 'Services and partnerships',
      elements: [
        {
          type: 'checkbox',
          name: 'services_interest',
          title: 'Would you pay for any of these as a service from Create or a trusted partner?',
          isRequired: false,
          choices: [
            'Site speed audit & fixes',
            'WordPress maintenance',
            'Schema / SEO audit & fixes',
            'Custom Create theme design to match your site',
            'AI workflow consulting',
            'Migration help from another plugin',
            'None right now',
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
      ],
    },
    {
      name: 'final',
      title: 'Final',
      elements: [
        {
          type: 'comment',
          name: 'open_feedback',
          title: 'Anything else you want me to know? Ideas, dreams, complaints?',
          isRequired: false,
        },
        {
          type: 'radiogroup',
          name: 'followup_call_optin',
          title: 'Can I follow up with you for a short call about your answers?',
          isRequired: true,
          choices: ['Yes', 'No'],
        },
        {
          type: 'text',
          name: 'followup_email',
          title: 'Best email to reach you?',
          inputType: 'email',
          isRequired: false,
          visibleIf: '{followup_call_optin} = "Yes"',
          validators: [{ type: 'email' }],
        },
      ],
    },
  ],
}

export const aprilSurveyPromotion = {
  discount: '50% off first year of Create Pro',
  delivery: 'Code shown on post-survey thank-you screen',
  window: 'April 2026',
  expires_at: '2026-05-03T23:59:59-04:00',
}
