/**
 * April 2026 Publisher Survey — SurveyJS format
 *
 * Converted from the original survey spec JSON.
 * Question types mapped:
 *   single_select → radiogroup
 *   multi_select  → checkbox
 *   scale (0-10)  → rating (rateMin/rateMax)
 *   scale (1-5)   → rating
 *   agree_scale   → rating (with agree/disagree labels)
 *   long_text     → comment
 *   rank          → ranking
 *   email         → text (inputType: email)
 */

export const aprilSurveyDefinition = {
  title: 'Create Publisher Survey — April 2026',
  description: 'Help shape the next chapter of Create. 5–10 minutes. Finish to unlock 50% off your first year of Create Pro.',
  showProgressBar: 'top',
  progressBarType: 'questions',
  showQuestionNumbers: 'off',
  questionErrorLocation: 'bottom',
  pages: [
    // Block 0: NPS
    {
      name: 'nps',
      title: 'NPS',
      elements: [
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'nps_score',
          title: 'On a scale of 0–10, how likely are you to recommend Create to another publisher?',
          isRequired: true,
          rateMin: 0,
          rateMax: 10,
          minRateDescription: 'Not at all likely',
          maxRateDescription: 'Extremely likely',
        },
        {
          type: 'comment',
          name: 'nps_reason',
          title: "What's the main reason for your score?",
          isRequired: false,
        },
      ],
    },
    // Block 1: Who you are
    {
      name: 'who_you_are',
      title: 'Who you are',
      elements: [
        {
          type: 'radiogroup',
          name: 'site_type',
          title: 'What best describes your site?',
          isRequired: true,
          choices: ['Food blog / Recipe site', 'DIY or craft', 'Home & garden', 'Parenting or lifestyle', 'Travel'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'tenure',
          title: 'How long have you been publishing?',
          isRequired: true,
          choices: ['Less than 1 year', '1–3 years', '3–7 years', '7–15 years', '15+ years'],
        },
        {
          type: 'radiogroup',
          name: 'monthly_sessions',
          title: 'Approximate monthly sessions on your site?',
          isRequired: true,
          choices: ['Under 10k', '10k–50k', '50k–200k', '200k–1M', '1M+'],
        },
        {
          type: 'radiogroup',
          name: 'ad_network',
          title: 'Which ad network are you on?',
          isRequired: false,
          choices: ['Raptive', 'Mediavine / Journey by Mediavine', 'Ezoic', 'Google AdSense only', 'Not monetized with display ads'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'annual_revenue',
          title: 'Approximate annual revenue from the site? (Optional — helps me price fairly)',
          isRequired: false,
          choices: ['Under $10k', '$10k–$50k', '$50k–$150k', '$150k–$500k', '$500k+', 'Prefer not to say'],
        },
      ],
    },
    // Block 2: State of the industry
    {
      name: 'state_of_industry',
      title: 'State of the industry',
      elements: [
        {
          type: 'radiogroup',
          name: 'traffic_trend',
          title: 'How is your traffic trending vs. 12 months ago?',
          isRequired: true,
          choices: ['Up significantly', 'Up slightly', 'Flat', 'Down slightly', 'Down significantly'],
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'ai_worry',
          title: 'How worried are you about AI Overviews and AI chat tools impacting your traffic?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not at all worried',
          maxRateDescription: 'Extremely worried',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_know_next_step',
          title: 'I feel like I know what to do next to grow my site.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_tools_keeping_up',
          title: 'The tools and plugins I use are keeping up with how publishing is changing.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'comment',
          name: 'biggest_worry',
          title: 'What is your single biggest worry about your publishing business right now?',
          isRequired: false,
        },
      ],
    },
    // Block 3: Positioning statements
    {
      name: 'positioning',
      title: 'Positioning statements',
      description: 'Rate your agreement with each statement (1 = strongly disagree, 5 = strongly agree).',
      elements: [
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_cited_by_humans_and_ai',
          title: 'I want my content to be the source that both humans and AI systems cite and return to.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_engagement_matters_more',
          title: 'Keeping readers engaged on my site matters more to me now than it did two years ago.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_pay_more_to_compete_with_ai',
          title: "I'd pay more for a plugin that actively helps me compete with AI-generated content.",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_community_over_library',
          title: 'I want my site to feel more like a community and less like a content library.',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_own_relationship',
          title: "I'd rather own the reader relationship (email, on-site engagement) than rely on Google traffic.",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
      ],
    },
    // Block 4: Current stack and spend
    {
      name: 'stack_and_spend',
      title: 'Current stack and spend',
      elements: [
        {
          type: 'checkbox',
          name: 'current_paid_tools',
          title: 'Which of these do you currently pay for?',
          isRequired: true,
          choices: [
            'WordPress hosting',
            'Recipe / content plugin (other than Create)',
            'SEO tool (Ahrefs, Semrush, etc.)',
            'Email service (Kit, ConvertKit, Flodesk, etc.)',
            'Email list cleaning / deliverability',
            'Pinterest scheduler',
            'Image CDN / optimization',
            'Site speed tools',
            'Virtual assistant',
            'Freelance developer',
            'Freelance designer',
            'Accounting / bookkeeping',
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'annual_tooling_spend',
          title: 'Roughly, total annual spend on site tools, services, and contractors?',
          isRequired: true,
          choices: ['Under $500', '$500–$2,000', '$2,000–$5,000', '$5,000–$15,000', '$15,000–$50,000', '$50,000+'],
        },
        {
          type: 'checkbox',
          name: 'competing_plugins_used',
          title: 'Which other recipe card or content plugin have you used, if any?',
          isRequired: false,
          choices: ['WP Recipe Maker', 'Tasty Recipes', 'Recipe Card Blocks', 'Cookbook', 'Zip Recipes', 'None'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'comment',
          name: 'stack_frustration',
          title: 'Biggest frustration with your current tool stack?',
          isRequired: false,
        },
      ],
    },
    // Block 5: Create specifically
    {
      name: 'create_specifically',
      title: 'Create specifically',
      elements: [
        {
          type: 'checkbox',
          name: 'create_primary_use',
          title: 'What do you use Create primarily for?',
          isRequired: true,
          choices: ['Recipe cards', 'How-to / tutorial cards', 'Lists / roundups', 'FAQs', 'All of the above'],
        },
        {
          type: 'ranking',
          name: 'feature_priorities_top_3',
          title: 'Which of these would you most want to see in Create next? Rank your top 3.',
          isRequired: true,
          choices: [
            'Interactive cook mode',
            'FAQ cards with schema',
            'Author cards (authority / E-E-A-T signals)',
            'Browser extension for saving links / products while browsing',
            'Mobile app for readers',
            'Community / network of Create publishers',
            'Content-discovery platform for readers',
            'Built-in AI recipe / content importer',
            'Built-in email capture / list features',
            'Speed & performance optimizations',
            'Better Pinterest integration',
          ],
          showOtherItem: true,
          otherText: 'Something else',
          selectToRankEnabled: true,
          selectToRankAreasLayout: 'horizontal',
          maxSelectedChoices: 3,
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'agree_top_feature_drives_pro',
          title: "If Create shipped my top-ranked feature above, I'd upgrade to Pro or stay on Pro.",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Strongly disagree',
          maxRateDescription: 'Strongly agree',
        },
        {
          type: 'comment',
          name: 'missing_to_be_indispensable',
          title: "What's missing from Create that would make it indispensable to you?",
          isRequired: false,
        },
      ],
    },
    // Block 6: Bigger bets
    {
      name: 'bigger_bets',
      title: 'Bigger bets — platform, community, extension',
      elements: [
        {
          type: 'radiogroup',
          name: 'discovery_app_interest',
          title: 'Imagine a reader-facing mobile app where people discover recipes and guides from Create publishers — they follow topics, rate content, and get recommendations. Your content could be included (opt-in). How do you feel about this?',
          isRequired: true,
          choices: [
            'Very interested — want in early',
            'Interested if I keep control and get paid',
            'Neutral — need more info',
            'Skeptical but open',
            'Not for me',
          ],
        },
        {
          type: 'radiogroup',
          name: 'discovery_app_model_pref',
          title: 'If such an app existed, which monetization model would you prefer?',
          isRequired: false,
          choices: [
            'Revenue share — app monetizes (ads / affiliates / subscriptions), we split',
            'Pro-only perk — my content, my monetization, Create takes nothing',
            'Flat licensing fee paid to me',
            "I wouldn't participate",
          ],
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'publisher_community_interest',
          title: "A private community of Create publishers where you could peer-review each other's content and cross-reference each other's lists/roundups — how interested are you?",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not interested',
          maxRateDescription: 'Very interested',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'browser_extension_interest',
          title: 'A browser extension for saving links and products to Create lists while you browse — how interested are you?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not interested',
          maxRateDescription: 'Very interested',
        },
      ],
    },
    // Block 7: AI
    {
      name: 'ai',
      title: 'AI',
      elements: [
        {
          type: 'checkbox',
          name: 'ai_tools_used',
          title: 'Which AI tools do you currently use for your publishing work?',
          isRequired: true,
          choices: ['ChatGPT', 'Claude', 'Gemini', 'Perplexity', 'Midjourney / image AI', 'AI writing tools (Jasper, etc.)', 'None'],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'rating',
          displayMode: 'buttons',
          name: 'ai_in_create_comfort',
          title: 'How comfortable are you with AI features being built into Create?',
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: 'Not comfortable',
          maxRateDescription: 'Very comfortable',
        },
        {
          type: 'checkbox',
          name: 'ai_features_wanted',
          title: 'Which AI-powered features would you actually use?',
          isRequired: false,
          choices: [
            'Recipe import from URL',
            'Auto-generate FAQs from existing content',
            'Nutrition estimation',
            'Image alt text generation',
            'SEO metadata suggestions',
            'Content ideas based on my existing library',
            'Answering reader questions on-site',
            'None of these',
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
      ],
    },
    // Block 8: Services and partnerships
    {
      name: 'services',
      title: 'Services and partnerships',
      elements: [
        {
          type: 'checkbox',
          name: 'services_interest',
          title: 'Would you pay for any of these as a service from Create or a trusted partner?',
          isRequired: false,
          choices: [
            'Site speed audit',
            'WordPress maintenance',
            'Recipe schema / SEO audit',
            'Pinterest pin design',
            'Custom site design',
            'Content strategy consulting',
            'AI workflow setup',
            'Migration from another recipe plugin',
            'None right now',
          ],
          showOtherItem: true,
          otherText: 'Other',
        },
        {
          type: 'radiogroup',
          name: 'services_budget',
          title: 'What would you expect to pay annually for the services you checked?',
          isRequired: false,
          choices: ['Under $500', '$500–$1,500', '$1,500–$5,000', '$5,000+', 'Depends entirely on scope'],
        },
      ],
    },
    // Block 9: Final
    {
      name: 'final',
      title: 'Final',
      elements: [
        {
          type: 'comment',
          name: 'open_feedback',
          title: 'Anything else you want me to know? Wishes, complaints, ideas — I read every response.',
          isRequired: false,
        },
        {
          type: 'radiogroup',
          name: 'followup_call_optin',
          title: 'Can I follow up with you for a 20-minute call about your answers?',
          isRequired: true,
          choices: ['Yes', 'No'],
        },
        {
          type: 'text',
          name: 'followup_email',
          title: 'Best email to reach you?',
          inputType: 'email',
          isRequired: false,
          visibleIf: '{followup_call_optin} = "Yes"',
          validators: [{ type: 'email' }],
        },
      ],
    },
  ],
}

export const aprilSurveyPromotion = {
  discount: '50% off first year of Create Pro',
  delivery: 'Code shown on post-survey thank-you screen',
  window: 'April 2026',
}
