#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Remove docs package from monorepo

set -e

echo "========================================"
echo "Create Studio - Development Environment"
echo "========================================"
echo ""
echo "NOTE: This script is for AFTER docs removal."
echo "Before removal, the docs package exists."
echo "After removal, only app, widgets, and shared will start."
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK IF DOCS PACKAGE EXISTS
# ============================================

if [ -d "packages/docs" ]; then
    echo -e "${YELLOW}WARNING: docs package still exists!${NC}"
    echo "This script is designed to run AFTER docs removal."
    echo "The docs package should be deleted first."
    echo ""
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# ============================================
# CLEAN INSTALL
# ============================================

echo ""
echo "Installing dependencies..."
cd /Users/jm/Sites/create-studio
npm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."
echo ""

# Shared library (watch mode for development)
echo "Starting shared library (watch mode)..."
cd /Users/jm/Sites/create-studio/packages/shared
npm run dev &

# Wait a moment for shared to build
sleep 2

# Widgets service
echo "Starting widgets service..."
cd /Users/jm/Sites/create-studio/packages/widgets
npm run dev &
wait_for_service 5173 "Widgets"

# App service
echo "Starting app service..."
cd /Users/jm/Sites/create-studio/packages/app
npm run dev &
wait_for_service 3001 "App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  App:     http://localhost:3001"
echo "  Widgets: http://localhost:5173"
echo "  Shared:  (library - watch mode active)"
echo ""
echo "Docs package: REMOVED (no longer running)"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
