#!/usr/bin/env node
/**
 * Prebuild script for admin package
 *
 * Fixes tsconfig issues that cause build failures:
 * 1. Creates minimal stub for main app's .nuxt/tsconfig.json
 * 2. Adds baseUrl to admin's .nuxt/tsconfig.json (generated by nuxt prepare)
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const adminRoot = join(__dirname, '..')
const appRoot = join(__dirname, '../../app')

// 1. Create minimal stub for main app's .nuxt/tsconfig.json
const appNuxtDir = join(appRoot, '.nuxt')
const appTsconfig = join(appNuxtDir, 'tsconfig.json')

mkdirSync(appNuxtDir, { recursive: true })
writeFileSync(appTsconfig, JSON.stringify({
  compilerOptions: {
    baseUrl: '.',
    paths: {}
  }
}, null, 2))
console.log('✓ Created main app .nuxt/tsconfig.json stub')

// 2. Add baseUrl to admin's .nuxt/tsconfig.json if it exists
const adminTsconfig = join(adminRoot, '.nuxt/tsconfig.json')

if (existsSync(adminTsconfig)) {
  try {
    const config = JSON.parse(readFileSync(adminTsconfig, 'utf-8'))
    if (config.compilerOptions && !config.compilerOptions.baseUrl) {
      config.compilerOptions.baseUrl = '.'
      writeFileSync(adminTsconfig, JSON.stringify(config, null, 2))
      console.log('✓ Added baseUrl to admin .nuxt/tsconfig.json')
    }
  } catch (err) {
    console.warn('⚠ Could not patch admin tsconfig:', err.message)
  }
}

console.log('✓ Prebuild complete')
